language: php

addons:
  postgresql: "9.4"

php:
    - 5.5
    - 5.6
    - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - phpenv config-rm xdebug.ini
    - composer install --dev --no-scripts
    - psql -c 'create database core_api;' -U postgres
    - cp .env.testing .env

script:
     - php vendor/bin/phpunit
     - php vendor/bin/php-cs-fixer --diff --dry-run -v --level=symfony --fixers=-psr0 fix .
